version: '2'
services:
    hipsterhouses-elasticsearch:
        container_name: hipsterhouses-elasticsearch
        image: elasticsearch:2.4.0
        # volumes:
        #     - ~/volumes/jhipster/hipsterHouses/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
